#ifndef WM_OBLIV_SELECT_H_
#define WM_OBLIV_SELECT_H_

#include <array>
#include <cstdint>
#include <vector>

#include "FssWM/fss/dpf_eval.h"
#include "FssWM/fss/dpf_gen.h"
#include "FssWM/fss/dpf_key.h"
#include "FssWM/sharing/share_types.h"

namespace fsswm {

class Channels;

namespace sharing {

class BinaryReplicatedSharing3P;
class BinarySharing2P;

}    // namespace sharing

namespace fss {
namespace prg {

class PseudoRandomGenerator;

}    // namespace prg
}    // namespace fss

namespace wm {

/**
 * @brief A class to hold params for the Oblivious Selection.
 */
class OblivSelectParameters {
public:
    /**
     * @brief Default constructor for OblivSelectParameters is deleted.
     */
    OblivSelectParameters() = delete;

    /**
     * @brief Parameterized constructor for OblivSelectParameters.
     * @param d The input bitsize.
     */
    explicit OblivSelectParameters(const uint64_t d, fss::OutputMode mode = fss::OutputMode::kBinaryPoint)
        : params_(d, 1, fss::EvalType::kIterSingleBatch, mode) {
    }

    /**
     * @brief Reconfigure the parameters for the Zero Test technique.
     * @param d The input bitsize.
     */
    void ReconfigureParameters(const uint64_t d, const fss::OutputMode mode = fss::OutputMode::kBinaryPoint) {
        params_.ReconfigureParameters(d, 1, fss::EvalType::kIterSingleBatch, mode);
    }

    /**
     * @brief Get the database size for the OblivSelectParameters.
     * @return uint64_t The input bitsize of DPF parameters.
     */
    uint64_t GetDatabaseSize() const {
        return params_.GetInputBitsize();
    }

    /**
     * @brief Get the DpfParameters for the OblivSelectParameters.
     * @return fss::dpf::DpfParameters The DpfParameters for the OblivSelectParameters.
     */
    const fss::dpf::DpfParameters GetParameters() const {
        return params_;
    }

    /**
     * @brief Get the string representation of the DpfParameters.
     * @return std::string The string representation of the DpfParameters.
     */
    std::string GetParametersInfo() const {
        return params_.GetParametersInfo();
    }

    /**
     * @brief Print the details of the DpfParameters.
     */
    void PrintParameters() const;

private:
    fss::dpf::DpfParameters params_; /**< DpfParameters for the OblivSelectParameters. */
};

/**
 * @brief A struct representing a key for the Oblivious Selection.
 */
struct OblivSelectKey {
    uint64_t         party_id;  /**< The ID of the party associated with the key. */
    fss::dpf::DpfKey prev_key;  /**< The DpfKey received from the previous party. */
    fss::dpf::DpfKey next_key;  /**< The DpfKey received from the next party. */
    uint64_t         prev_r_sh; /**< The share r received from the previous party. */
    uint64_t         next_r_sh; /**< The share r received from the next party. */
    uint64_t         r;         /**< Sampled random number generated by the party. */
    uint64_t         r_sh_0;    /**< The share r for 0. */
    uint64_t         r_sh_1;    /**< The share r for 1. */

    /**
     * @brief Default constructor for OblivSelectKey is deleted.
     */
    OblivSelectKey() = delete;

    /**
     * @brief Parameterized constructor for OblivSelectKey.
     * @param id The ID of the party associated with the key.
     * @param params OblivSelectParameters for the OblivSelectKey.
     */
    OblivSelectKey(const uint64_t id, const OblivSelectParameters &params);

    /**
     * @brief Destructor for OblivSelectKey.
     */
    ~OblivSelectKey() = default;

    /**
     * @brief Copy constructor is deleted to prevent copying of OblivSelectKey.
     */
    OblivSelectKey(const OblivSelectKey &)            = delete;
    OblivSelectKey &operator=(const OblivSelectKey &) = delete;

    /**
     * @brief Move constructor for OblivSelectKey.
     */
    OblivSelectKey(OblivSelectKey &&)            = default;
    OblivSelectKey &operator=(OblivSelectKey &&) = default;

    /**
     * @brief Equality operator for OblivSelectKey.
     * @param rhs The OblivSelectKey to compare against.
     * @return True if the OblivSelectKey is equal, false otherwise.
     */
    bool operator==(const OblivSelectKey &rhs) const {
        return (party_id == rhs.party_id) && (prev_key == rhs.prev_key) && (next_key == rhs.next_key) &&
               (prev_r_sh == rhs.prev_r_sh) && (next_r_sh == rhs.next_r_sh) &&
               (r == rhs.r) && (r_sh_0 == rhs.r_sh_0) && (r_sh_1 == rhs.r_sh_1);
    }

    bool operator!=(const OblivSelectKey &rhs) const {
        return !(*this == rhs);
    }

    /**
     * @brief Get the size of the serialized OblivSelectKey.
     * @return size_t The size of the serialized OblivSelectKey.
     */
    size_t GetSerializedSize() const {
        return serialized_size_;
    }

    /**
     * @brief Calculate the size of the serialized OblivSelectKey.
     * @return size_t The size of the serialized OblivSelectKey.
     */
    size_t CalculateSerializedSize() const;

    /**
     * @brief Serialize the OblivSelectKey.
     * @param buffer The buffer to store the serialized OblivSelectKey.
     */
    void Serialize(std::vector<uint8_t> &buffer) const;

    /**
     * @brief Deserialize the OblivSelectKey.
     * @param buffer The buffer to store the serialized OblivSelectKey.
     */
    void Deserialize(const std::vector<uint8_t> &buffer);

    /**
     * @brief Print the OblivSelectKey.
     * @param detailed Flag to print the detailed OblivSelectKey.
     */
    void PrintKey(const bool detailed = false) const;

private:
    OblivSelectParameters params_;          /**< OblivSelectParameters for the OblivSelectKey. */
    size_t                serialized_size_; /**< The size of the serialized OblivSelectKey. */
};

/**
 * @brief A class to generate keys for the Oblivious Selection.
 */
class OblivSelectKeyGenerator {
public:
    /**
     * @brief Default constructor for OblivSelectKeyGenerator is deleted.
     */
    OblivSelectKeyGenerator() = delete;

    /**
     * @brief Parameterized constructor for OblivSelectKeyGenerator.
     * @param params OblivSelectParameters for the OblivSelectKeyGenerator.
     * @param bss Binary sharing for 2-party for the OblivSelectKeyGenerator.
     */
    OblivSelectKeyGenerator(const OblivSelectParameters &params,
                            sharing::BinarySharing2P    &bss);

    /**
     * @brief Generate keys for the Oblivious Selection.
     * @return std::array<OblivSelectKey, 3> The array of OblivSelectKey for the Oblivious Selection.
     */
    std::array<OblivSelectKey, 3> GenerateKeys() const;

private:
    OblivSelectParameters     params_; /**< OblivSelectParameters for the OblivSelectKeyGenerator. */
    fss::dpf::DpfKeyGenerator gen_;    /**< DPF key generator for the OblivSelectKeyGenerator. */
    sharing::BinarySharing2P &bss_;    /**< Binary sharing for 2-party for the OblivSelectKeyGenerator. */
};

/**
 * @brief A class to evaluate keys for the Oblivious Selection.
 */
class OblivSelectEvaluator {
public:
    /**
     * @brief Default constructor for OblivSelectEvaluator is deleted.
     */
    OblivSelectEvaluator() = delete;

    /**
     * @brief Parameterized constructor for OblivSelectEvaluator.
     * @param params OblivSelectParameters for the OblivSelectEvaluator.
     * @param rss Replicated sharing for 3-party for the OblivSelectEvaluator.
     * @param brss Binary replicated sharing for 3-party for the OblivSelectEvaluator.
     */
    OblivSelectEvaluator(const OblivSelectParameters        &params,
                         sharing::BinaryReplicatedSharing3P &brss);

    void Evaluate(Channels                         &chls,
                  const OblivSelectKey             &key,
                  const sharing::RepShareViewBlock &database,
                  const sharing::RepShare64        &index,
                  sharing::RepShareBlock           &result) const;

    block FullDomainDotProduct(const fss::dpf::DpfKey       &key,
                               const std::span<const block> &database,
                               const uint64_t                pr) const;

    void Evaluate_FdeThenDP(Channels                      &chls,
                            const OblivSelectKey          &key,
                            std::vector<block>            &uv_prev,
                            std::vector<block>            &uv_next,
                            const sharing::RepShareView64 &database,
                            const sharing::RepShare64     &index,
                            sharing::RepShare64           &result) const;

    void Evaluate_FdeThenDP(Channels                      &chls,
                            const OblivSelectKey          &key,
                            std::vector<block>            &uv_prev,
                            std::vector<block>            &uv_next,
                            const sharing::RepShareView64 &database1,
                            const sharing::RepShareView64 &database2,
                            const sharing::RepShare64     &index,
                            sharing::RepShare64           &result1,
                            sharing::RepShare64           &result2) const;

    uint64_t FullDomainDotProduct_FdeThenDP(const fss::dpf::DpfKey      &key,
                                            std::vector<block>          &outputs,
                                            const std::vector<uint64_t> &database,
                                            const uint64_t               pr) const;

private:
    OblivSelectParameters               params_; /**< OblivSelectParameters for the OblivSelectEvaluator. */
    fss::dpf::DpfEvaluator              eval_;   /**< DPF evaluator for the OblivSelectEvaluator. */
    sharing::BinaryReplicatedSharing3P &brss_;   /**< Binary replicated sharing for 3-party for the OblivSelectEvaluator. */
    fss::prg::PseudoRandomGenerator    &G_;      /**< Pseudo random generator for the OblivSelectEvaluator. */

    // Internal functions
    std::pair<uint64_t, uint64_t> ReconstructPRBinary(Channels                  &chls,
                                                      const OblivSelectKey      &key,
                                                      const sharing::RepShare64 &index) const;

    void EvaluateNextSeed(const uint64_t current_level, const block &current_seed, const bool &current_control_bit,
                          std::array<block, 2> &expanded_seeds, std::array<bool, 2> &expanded_control_bits,
                          const fss::dpf::DpfKey &key) const;
};

}    // namespace wm
}    // namespace fsswm

#endif    // WM_OBLIV_SELECT_H_
