#ifndef WM_ZERO_TEST_H_
#define WM_ZERO_TEST_H_

#include "FssWM/fss/dpf_eval.h"
#include "FssWM/fss/dpf_gen.h"
#include "FssWM/fss/dpf_key.h"

namespace fsswm {

namespace sharing {

class ReplicatedSharing3P;
class BinaryReplicatedSharing3P;
class AdditiveSharing2P;
class BinarySharing2P;
class RepShareVec;
class RepShare;
struct Channels;

}    // namespace sharing

namespace fm_index {

/**
 * @brief A class to hold params for the Zero Test.
 */
class ZeroTestParameters {
public:
    /**
     * @brief Default constructor for ZeroTestParameters is deleted.
     */
    ZeroTestParameters() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestParameters.
     * @param n The input bitsize.
     * @param type The type of sharing.
     */
    explicit ZeroTestParameters(const uint32_t n, const ShareType type)
        : params_(n, type == ShareType::kAdditive ? n : 1), type_(type) {
    }

    /**
     * @brief Reconfigure the parameters for the Zero Test.
     * @param n The input bitsize.
     */
    void ReconfigureParameters(const uint32_t n, const ShareType type) {
        params_.ReconfigureParameters(n, type == ShareType::kAdditive ? n : 1);
        type_ = type;
    }

    /**
     * @brief Get the DPF parameters for the Zero Test.
     * @return fss::dpf::DpfParameters The DPF parameters for the Zero Test.
     */
    fss::dpf::DpfParameters GetParameters() const {
        return params_;
    }

    /**
     * @brief Get the type of sharing for the Zero Test.
     * @return ShareType The type of sharing for the Zero Test.
     */
    ShareType GetType() const {
        return type_;
    }

    /**
     * @brief Get the string representation of the ZeroTestParameters.
     * @return std::string The string representation of the ZeroTestParameters.
     */
    std::string GetParametersInfo() const {
        return params_.GetParametersInfo() + " | ShareType: " + (type_ == ShareType::kAdditive ? "Additive" : "Binary");
    }

    /**
     * @brief Print the details of the ZeroTestParameters.
     */
    void PrintParameters() const;

private:
    fss::dpf::DpfParameters params_; /**< DpfParameters for the ZeroTestParameters. */
    ShareType               type_;   /**< The type of sharing for the ZeroTestParameters. */
};

/**
 * @brief A struct representing a key for the Zero Test.
 */
struct ZeroTestKey {
    uint32_t         party_id;  /**< The ID of the party associated with the key. */
    fss::dpf::DpfKey prev_key;  /**< The DpfKey received from the previous party. */
    fss::dpf::DpfKey next_key;  /**< The DpfKey received from the next party. */
    uint32_t         prev_r_sh; /**< The share r received from the previous party. */
    uint32_t         next_r_sh; /**< The share r received from the next party. */
    uint32_t         r;         /**< Sampled random number generated by the party. */
    uint32_t         r_sh_0;    /**< The share r for 0. */
    uint32_t         r_sh_1;    /**< The share r for 1. */

    /**
     * @brief Default constructor for ZeroTestKey is deleted.
     */
    ZeroTestKey() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestKey.
     * @param id The ID of the party associated with the key.
     * @param params ZeroTestParameters for the ZeroTestKey.
     */
    ZeroTestKey(const uint32_t id, const ZeroTestParameters &params);

    /**
     * @brief Destructor for ZeroTestKey.
     */
    ~ZeroTestKey() = default;

    /**
     * @brief Copy constructor is deleted to prevent copying of ZeroTestKey.
     */
    ZeroTestKey(const ZeroTestKey &)            = delete;
    ZeroTestKey &operator=(const ZeroTestKey &) = delete;

    /**
     * @brief Move constructor for ZeroTestKey.
     */
    ZeroTestKey(ZeroTestKey &&) noexcept            = default;
    ZeroTestKey &operator=(ZeroTestKey &&) noexcept = default;

    /**
     * @brief Equality operator for ZeroTestKey.
     * @param rhs The ZeroTestKey to compare against.
     * @return True if the ZeroTestKey is equal, false otherwise.
     */
    bool operator==(const ZeroTestKey &rhs) const {
        return (party_id == rhs.party_id) && (prev_key == rhs.prev_key) && (next_key == rhs.next_key) &&
               (prev_r_sh == rhs.prev_r_sh) && (next_r_sh == rhs.next_r_sh) &&
               (r == rhs.r) && (r_sh_0 == rhs.r_sh_0) && (r_sh_1 == rhs.r_sh_1);
    }

    bool operator!=(const ZeroTestKey &rhs) const {
        return !(*this == rhs);
    }

    /**
     * @brief Get the size of the serialized ZeroTestKey.
     * @return size_t The size of the serialized ZeroTestKey.
     */
    size_t GetSerializedSize() const {
        return serialized_size_;
    }

    /**
     * @brief Calculate the size of the serialized ZeroTestKey.
     * @return size_t The size of the serialized ZeroTestKey.
     */
    size_t CalculateSerializedSize() const;

    /**
     * @brief Serialize the ZeroTestKey.
     * @param buffer The serialized ZeroTestKey.
     */
    void Serialize(std::vector<uint8_t> &buffer) const;

    /**
     * @brief Deserialize the ZeroTestKey.
     * @param buffer The serialized ZeroTestKey.
     */
    void Deserialize(const std::vector<uint8_t> &buffer);

    /**
     * @brief Print the details of the ZeroTestKey.
     * @param detailed Flag to print detailed information.
     */
    void PrintKey(const bool detailed = false) const;

private:
    ZeroTestParameters params_;          /**< ZeroTestParameters for the ZeroTestKey. */
    size_t             serialized_size_; /**< The size of the serialized ZeroTestKey. */
};

/**
 * @brief A class to generate keys for the Zero Test.
 */
class ZeroTestKeyGenerator {
public:
    /**
     * @brief Default constructor for ZeroTestKeyGenerator is deleted.
     */
    ZeroTestKeyGenerator() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestKeyGenerator.
     * @param params ZeroTestParameters for the ZeroTestKeyGenerator
     * @param ass AAdditive sharing for 2-party for the ZeroTestKeyGenerator
     * @param bss Binary sharing for 2-party for the ZeroTestKeyGenerator.
     */
    ZeroTestKeyGenerator(
        const ZeroTestParameters   &params,
        sharing::AdditiveSharing2P &ass,
        sharing::BinarySharing2P   &bss);

    /**
     * @brief Generate keys for the Zero Test.
     * @return ZeroTestKey The ZeroTestKey for the Zero Test.
     */
    std::array<ZeroTestKey, 3> GenerateKeys() const;

private:
    ZeroTestParameters          params_; /**< ZeroTestParameters for the ZeroTestKeyGenerator. */
    fss::dpf::DpfKeyGenerator   gen_;    /**< DPF key generator for the ZeroTestKeyGenerator. */
    sharing::AdditiveSharing2P &ass_;    /**< Additive sharing for 2-party for the ZeroTestKeyGenerator. */
    sharing::BinarySharing2P   &bss_;    /**< Binary sharing for 2-party for the ZeroTestKeyGenerator. */

    // Internal functions
    void GenerateAdditiveKeys(std::array<ZeroTestKey, 3> &keys) const;    // TODO
    void GenerateBinaryKeys(std::array<ZeroTestKey, 3> &keys) const;
};

/**
 * @brief A class to evaluate keys for the Zero Test.
 */
class ZeroTestEvaluator {
public:
    /**
     * @brief Default constructor for ZeroTestEvaluator is deleted.
     */
    ZeroTestEvaluator() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestEvaluator.
     * @param params ZeroTestParameters for the ZeroTestEvaluator.
     * @param rss Replicated sharing for 3-party for the ZeroTestEvaluator.
     * @param brss Binary replicated sharing for 3-party for the ZeroTestEvaluator.
     */
    ZeroTestEvaluator(
        const ZeroTestParameters           &params,
        sharing::ReplicatedSharing3P       &rss,
        sharing::BinaryReplicatedSharing3P &brss);

    /**
     * @brief Evaluate the Zero Test.
     * @param chls Channels for the Zero Test.
     * @param key The ZeroTestKey for the Zero Test.
     * @param x The input for the Zero Test.
     * @param result The result for the Zero Test.
     */
    void EvaluateAdditive(sharing::Channels       &chls,
                          const ZeroTestKey       &key,
                          const sharing::RepShare &x,
                          sharing::RepShare       &result) const;    // TODO

    /**
     * @brief Evaluate the Zero Test.
     * @param chls Channels for the Zero Test.
     * @param key The ZeroTestKey for the Zero Test.
     * @param x The input for the Zero Test.
     * @param result The result for the Zero Test.
     */
    void EvaluateBinary(sharing::Channels       &chls,
                        const ZeroTestKey       &key,
                        const sharing::RepShare &x,
                        sharing::RepShare       &result) const;

    /**
     * @brief Evaluate the Zero Test.
     * @param chls Channels for the Zero Test.
     * @param key The ZeroTestKey for the Zero Test.
     * @param x The input vector for the Zero Test.
     * @param result The result vector for the Zero Test.
     */
    void EvaluateBinary(sharing::Channels              &chls,
                        const std::vector<ZeroTestKey> &key,
                        const sharing::RepShareVec     &x,
                        sharing::RepShareVec           &result) const;

private:
    ZeroTestParameters                  params_; /**< ZeroTestParameters for the ZeroTestEvaluator. */
    fss::dpf::DpfEvaluator              eval_;   /**< DPF evaluator for the ZeroTestEvaluator. */
    sharing::ReplicatedSharing3P       &rss_;    /**< Replicated sharing for 3-party for the ZeroTestEvaluator. */
    sharing::BinaryReplicatedSharing3P &brss_;   /**< Binary replicated sharing for 3-party for the ZeroTestEvaluator. */

    // Internal functions
    std::pair<uint32_t, uint32_t> ReconstructPRAdditive(sharing::Channels       &chls,
                                                        const ZeroTestKey       &key,
                                                        const sharing::RepShare &x,
                                                        const uint32_t           n) const;

    std::pair<uint32_t, uint32_t> ReconstructPRBinary(sharing::Channels       &chls,
                                                      const ZeroTestKey       &key,
                                                      const sharing::RepShare &x) const;

    void ReconstructPRBinary(sharing::Channels              &chls,
                             const std::vector<ZeroTestKey> &key,
                             const sharing::RepShareVec     &x,
                             std::vector<uint32_t>          &res_prev,
                             std::vector<uint32_t>          &res_next) const;
};

}    // namespace fm_index
}    // namespace fsswm

#endif    // WM_ZERO_TEST_H_
