#ifndef WM_ZERO_TEST_H_
#define WM_ZERO_TEST_H_

#include "FssWM/fss/dpf_eval.h"
#include "FssWM/fss/dpf_gen.h"
#include "FssWM/fss/dpf_key.h"
#include "FssWM/sharing/share_types.h"

namespace fsswm {

struct Channels;

namespace sharing {

class BinaryReplicatedSharing3P;
class BinarySharing2P;

}    // namespace sharing

namespace fm_index {

/**
 * @brief A class to hold params for the Zero Test.
 */
class ZeroTestParameters {
public:
    /**
     * @brief Default constructor for ZeroTestParameters is deleted.
     */
    ZeroTestParameters() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestParameters.
     * @param n The input bitsize.
     */
    explicit ZeroTestParameters(const uint64_t n)
        : params_(n, 1) {
    }

    /**
     * @brief Reconfigure the parameters for the Zero Test.
     * @param n The input bitsize.
     */
    void ReconfigureParameters(const uint64_t n) {
        params_.ReconfigureParameters(n, 1);
    }

    /**
     * @brief Get the DPF parameters for the Zero Test.
     * @return fss::dpf::DpfParameters The DPF parameters for the Zero Test.
     */
    fss::dpf::DpfParameters GetParameters() const {
        return params_;
    }

    /**
     * @brief Get the string representation of the ZeroTestParameters.
     * @return std::string The string representation of the ZeroTestParameters.
     */
    std::string GetParametersInfo() const {
        return params_.GetParametersInfo();
    }

    /**
     * @brief Print the details of the ZeroTestParameters.
     */
    void PrintParameters() const;

private:
    fss::dpf::DpfParameters params_; /**< DpfParameters for the ZeroTestParameters. */
};

/**
 * @brief A struct representing a key for the Zero Test.
 */
struct ZeroTestKey {
    uint64_t         party_id;  /**< The ID of the party associated with the key. */
    fss::dpf::DpfKey prev_key;  /**< The DpfKey received from the previous party. */
    fss::dpf::DpfKey next_key;  /**< The DpfKey received from the next party. */
    uint64_t         prev_r_sh; /**< The share r received from the previous party. */
    uint64_t         next_r_sh; /**< The share r received from the next party. */
    uint64_t         r;         /**< Sampled random number generated by the party. */
    uint64_t         r_sh_0;    /**< The share r for 0. */
    uint64_t         r_sh_1;    /**< The share r for 1. */

    /**
     * @brief Default constructor for ZeroTestKey is deleted.
     */
    ZeroTestKey() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestKey.
     * @param id The ID of the party associated with the key.
     * @param params ZeroTestParameters for the ZeroTestKey.
     */
    ZeroTestKey(const uint64_t id, const ZeroTestParameters &params);

    /**
     * @brief Destructor for ZeroTestKey.
     */
    ~ZeroTestKey() = default;

    /**
     * @brief Copy constructor is deleted to prevent copying of ZeroTestKey.
     */
    ZeroTestKey(const ZeroTestKey &)            = delete;
    ZeroTestKey &operator=(const ZeroTestKey &) = delete;

    /**
     * @brief Move constructor for ZeroTestKey.
     */
    ZeroTestKey(ZeroTestKey &&) noexcept            = default;
    ZeroTestKey &operator=(ZeroTestKey &&) noexcept = default;

    /**
     * @brief Equality operator for ZeroTestKey.
     * @param rhs The ZeroTestKey to compare against.
     * @return True if the ZeroTestKey is equal, false otherwise.
     */
    bool operator==(const ZeroTestKey &rhs) const {
        return (party_id == rhs.party_id) && (prev_key == rhs.prev_key) && (next_key == rhs.next_key) &&
               (prev_r_sh == rhs.prev_r_sh) && (next_r_sh == rhs.next_r_sh) &&
               (r == rhs.r) && (r_sh_0 == rhs.r_sh_0) && (r_sh_1 == rhs.r_sh_1);
    }

    bool operator!=(const ZeroTestKey &rhs) const {
        return !(*this == rhs);
    }

    /**
     * @brief Get the size of the serialized ZeroTestKey.
     * @return size_t The size of the serialized ZeroTestKey.
     */
    size_t GetSerializedSize() const {
        return serialized_size_;
    }

    /**
     * @brief Calculate the size of the serialized ZeroTestKey.
     * @return size_t The size of the serialized ZeroTestKey.
     */
    size_t CalculateSerializedSize() const;

    /**
     * @brief Serialize the ZeroTestKey.
     * @param buffer The serialized ZeroTestKey.
     */
    void Serialize(std::vector<uint8_t> &buffer) const;

    /**
     * @brief Deserialize the ZeroTestKey.
     * @param buffer The serialized ZeroTestKey.
     */
    void Deserialize(const std::vector<uint8_t> &buffer);

    /**
     * @brief Print the details of the ZeroTestKey.
     * @param detailed Flag to print detailed information.
     */
    void PrintKey(const bool detailed = false) const;

private:
    ZeroTestParameters params_;          /**< ZeroTestParameters for the ZeroTestKey. */
    size_t             serialized_size_; /**< The size of the serialized ZeroTestKey. */
};

/**
 * @brief A class to generate keys for the Zero Test.
 */
class ZeroTestKeyGenerator {
public:
    /**
     * @brief Default constructor for ZeroTestKeyGenerator is deleted.
     */
    ZeroTestKeyGenerator() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestKeyGenerator.
     * @param params ZeroTestParameters for the ZeroTestKeyGenerator
     * @param bss Binary sharing for 2-party for the ZeroTestKeyGenerator.
     */
    ZeroTestKeyGenerator(const ZeroTestParameters &params,
                         sharing::BinarySharing2P &bss);

    /**
     * @brief Generate keys for the Zero Test.
     * @return ZeroTestKey The ZeroTestKey for the Zero Test.
     */
    std::array<ZeroTestKey, 3> GenerateKeys() const;

private:
    ZeroTestParameters        params_; /**< ZeroTestParameters for the ZeroTestKeyGenerator. */
    fss::dpf::DpfKeyGenerator gen_;    /**< DPF key generator for the ZeroTestKeyGenerator. */
    sharing::BinarySharing2P &bss_;    /**< Binary sharing for 2-party for the ZeroTestKeyGenerator. */
};

/**
 * @brief A class to evaluate keys for the Zero Test.
 */
class ZeroTestEvaluator {
public:
    /**
     * @brief Default constructor for ZeroTestEvaluator is deleted.
     */
    ZeroTestEvaluator() = delete;

    /**
     * @brief Parameterized constructor for ZeroTestEvaluator.
     * @param params ZeroTestParameters for the ZeroTestEvaluator.
     * @param brss Binary replicated sharing for 3-party for the ZeroTestEvaluator.
     */
    ZeroTestEvaluator(
        const ZeroTestParameters           &params,
        sharing::BinaryReplicatedSharing3P &brss);

    /**
     * @brief Evaluate the Zero Test.
     * @param chls Channels for the Zero Test.
     * @param key The ZeroTestKey for the Zero Test.
     * @param x The input for the Zero Test.
     * @param result The result for the Zero Test.
     */
    void Evaluate(Channels                  &chls,
                  const ZeroTestKey         &key,
                  const sharing::RepShare64 &x,
                  sharing::RepShare64       &result) const;

    /**
     * @brief Evaluate the Zero Test.
     * @param chls Channels for the Zero Test.
     * @param key The ZeroTestKey for the Zero Test.
     * @param x The input vector for the Zero Test.
     * @param result The result vector for the Zero Test.
     */
    void Evaluate(Channels                       &chls,
                  const std::vector<ZeroTestKey> &key,
                  const sharing::RepShareVec64   &x,
                  sharing::RepShareVec64         &result) const;

private:
    ZeroTestParameters                  params_; /**< ZeroTestParameters for the ZeroTestEvaluator. */
    fss::dpf::DpfEvaluator              eval_;   /**< DPF evaluator for the ZeroTestEvaluator. */
    sharing::BinaryReplicatedSharing3P &brss_;   /**< Binary replicated sharing for 3-party for the ZeroTestEvaluator. */

    // Internal functions
    std::pair<uint64_t, uint64_t> ReconstructPRBinary(Channels                  &chls,
                                                      const ZeroTestKey         &key,
                                                      const sharing::RepShare64 &x) const;

    void ReconstructPRBinary(Channels                       &chls,
                             const std::vector<ZeroTestKey> &key,
                             const sharing::RepShareVec64   &x,
                             std::vector<uint64_t>          &res_prev,
                             std::vector<uint64_t>          &res_next) const;
};

}    // namespace fm_index
}    // namespace fsswm

#endif    // WM_ZERO_TEST_H_
